# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Sentir es crear sentido
description:        Baile, saberes y afectos
lang:               es

# Site base hostname & protocol, e.g. http://example.com
url: 'daprieto1.github.io'

# Site subpath, e.g. /blog
baseurl:            "/SentirEsCrearSentido"

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink: /:title/

logo: img/navbar/logo.png
logo2x: img/navbar/logo.png
white_logo: img/navbar/logo.png
white_logo2x: img/navbar/logo.png


footer:
    copyright:     Â© 2021 All Rights Reserved Design by <a href="https://themeforest.net/user/spider-themes">Spider-themes</a>

# Social icons displayed in footer
social:
    facebook:       https://www.facebook.com/
    dribbble:
    instagram:      https://www.instagram.com/
    linkedin:       https://www.linkedin.com/
    pinterest:      
    twitter:        https://twitter.com/
    vimeo:          https://vimeo.com/
    youtube:

collections:
  docs:
    output: true

# Number of posts displayed on blog page
paginate:     7

# Blog path
paginate_path: "/blog/:num/"


# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:     #12345

# Google Analytics
google_analytics: "G-B9VN13S72X"

plugins:
  - jekyll-liquify
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

# Defaults
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: doc
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
